# Generated by Django 3.2.9 on 2022-02-08 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0204_orderposition_backfill_is_bundled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBWAYIfThenPayObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('orderID', models.CharField(db_index=True, max_length=190, unique=True)),
                ('mbway_key', models.CharField(max_length=11)),
                ('channel', models.CharField(max_length=3)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.order')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.orderpayment')),
            ],
        ),
    ]
