# Generated by Django 3.2.13 on 2022-06-20 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0216_checkin_forced_sent'),
        ('pretix_mbway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBWAYGatewayObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('transactionID', models.CharField(db_index=True, max_length=190, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.order')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.orderpayment')),
            ],
        ),
    ]
