# Generated by Django 3.2.13 on 2022-06-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_mbway', '0002_mbwaygatewayobject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MBWAYIfThenPayObject',
        ),
    ]
